Génération des identifiant +  modification TU
Prakkkmak/animaliste-back pull request #20
Opened 2021-02-04 17:12 UTC by BastienLamour

2021-02-04 17:13 UTC, BastienLamour commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajout d'un identifiant simple a gérer](https://trello.com/c/hWynRQ4J/58-ajout-dun-identifiant-simple-a-g%C3%A9rer)

2021-02-05 20:41 UTC, Prakkkmak requested changes

2021-02-05 20:41 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AnimalController.kt
> +                       private val documentSequenceDao: DocumentSequenceDao) {
le documentSequence n'a rien a faire dans le Controller, il dois intervenir dans le service dans le repo.insert

2021-02-05 20:41 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AnimalController.kt
> -class AnimalController(private val repository: AnimalRepository) {
utiliser service a la place de repo

2021-02-05 20:41 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/daos/DocumentSequenceDao.kt
> +interface DocumentSequenceDao {
a delete

2021-02-05 20:41 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/repositories/SequenceGenearatorDaoImpl.kt
> +class SequenceGenearatorDaoImpl(private val mongoOperations: MongoOperations) : DocumentSequenceDao {
DaoImpl => Service

2021-02-05 20:41 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/repositories/SequenceGenearatorDaoImpl.kt
> +@Repository
@Service

2021-02-06 18:34 UTC, Prakkkmak approved these changes

2021-02-06 18:34 UTC, merged