Gestion des images
Prakkkmak/animaliste-back pull request #23
Opened 2021-02-13 16:14 UTC by BastienLamour

2021-02-13 16:14 UTC, BastienLamour commented
![](https://github.trello.services/images/mini-trello-icon.png) [Gestion des images - back](https://trello.com/c/2ajIz3xo/144-gestion-des-images-back)

2021-02-13 17:18 UTC, Prakkkmak requested changes

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        val pictureNamePath : Path = Paths.get(pictureStorageDto::name.get())
pictureStorageDto.name

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +    fun store(category: String, pictureStorageDto: PictureStorageDto) : PictureStorageDto{
```suggestion
    fun store(category: String, picture: PictureStorageDto) : PictureStorageDto{
```

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/dtos/PictureStorageDto.kt
> +data class PictureStorageDto(
```suggestion
data class PictureDto(
```
Le nom que je préconise. En effet, le dto n'est pas un storage

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        if(!Files.exists(pictureNamePath)) Files.createDirectory(pictureNamePath)
Tu ne créé pas de folder dans la categorie

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        Files.copy(pictureStorageDto::file.get().inputStream, pictureNamePath)
Tu store a la racine des images

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +    fun store(category: String, pictureStorageDto: PictureStorageDto) : PictureStorageDto{
pourquoi store et pas save ?

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +    fun store(category: String, pictureStorageDto: PictureStorageDto) : PictureStorageDto{
La méthode devrais déjà sauvegarder les images dans un dossier images et enregistrer les photos dans le dossier 'category' dans le sous dossier du nom de l'image.

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        Files.copy(pictureStorageDto::file.get().inputStream, pictureNamePath)
on a dis que l'image devrais se nommer "1" dans le sous dossier de nom le nom.

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/PictureController.kt
> +    fun uploadImage(@PathVariable("category") category: String,
On ne renvoie plus de ResponseEntity mais bien le Dto directement

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/PictureController.kt
> +    : ResponseEntity<Resource>{
On ne renvoie plus de ResponseEntity

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        if(!Files.exists(categoryPath) || !Files.exists(picturePath)) throw ResourceNotFoundException()
Files.exists(categoryPath) n'est pas necessaire de tester car la picture est dans le folder a priori

2021-02-13 17:18 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        val picturePath: Path = categoryPath.resolve(name)
Mhh que faire si le nom de la categorie est mauvais ?

2021-02-14 16:36 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        if(!Files.exists(pictureNamePath)) Files.createDirectory(pictureNamePath)
On ne doit pas avoir un chemin du genre : 
Animal
   [ID ou NOM]
      1.png

par exemple ?

2021-02-14 16:37 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        Files.copy(pictureStorageDto::file.get().inputStream, pictureNamePath)
Je comprends pas ce commentaire

2021-02-14 16:37 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        Files.copy(pictureStorageDto::file.get().inputStream, pictureNamePath)
Pareil, ton commentaire semble incohérent avec ce que tu dit plus haut sur la catégorie

2021-02-14 16:38 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        val picturePath: Path = categoryPath.resolve(name)
Il est testé plus bas

2021-02-14 16:39 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        if(!Files.exists(categoryPath) || !Files.exists(picturePath)) throw ResourceNotFoundException()
C'est justement pour tester si le nom de la catégorie est bon

2021-02-14 16:47 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        Files.copy(pictureStorageDto::file.get().inputStream, pictureNamePath)
Tu envoie le fichier a la racine du dossier "images"

2021-02-14 16:47 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/services/PictureStorageService.kt
> +        if(!Files.exists(pictureNamePath)) Files.createDirectory(pictureNamePath)
Sisi

2021-03-05 10:12 UTC, merged