Ajout de la DataClass Account, de son repository et controller.
Prakkkmak/animaliste-back pull request #8
Opened 2021-01-02 15:26 UTC by BastienLamour

Ajout des méthodes nécessaires au CRUD d'un compte utilisateur.

2021-01-02 15:30 UTC, BastienLamour commented
![](https://github.trello.services/images/mini-trello-icon.png) [Comptes](https://trello.com/c/e6IfB5G7/46-comptes)

2021-01-02 15:53 UTC, Prakkkmak requested changes

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +@RequestMapping("/admin")
Pluriel pour le mapping d'un controller

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +@RequestMapping("/admin")
J'aurais nommé le mapping accounts

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +     * Récupère tous les comptes
Ponctuation

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +     * Ajoute un compte
Ponctuation

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +     * Modifie le compte en fonction de son identifiant et des nouvelles données
Ponctuation

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +     * Supprime le compte en fonction de son identifiant
Ponctuation

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/entities/Account.kt
> +import java.util.*
Import * en trop

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/repositories/AccountRepository.kt
> +interface AccountRepository : MongoRepository<Account, String> {
Ajout de findByMail
Ajout de findByMail+Mdp

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/entities/Account.kt
> +    val id: String = ObjectId.get().toString(),
```suggestion
    val id: String = ObjectId.get().toString(),
    val mail: String,
    val password: String,
```

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/entities/Account.kt
> +    val name: String,
```suggestion
    val name: String?,
```

2021-01-02 15:53 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/entities/Account.kt
> +    val contact: String,
```suggestion
    val surname: String?,
    val phoneNumber: String?,
```

2021-01-04 21:15 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getOneAccountByMail(@PathVariable("mail") mail: String, @RequestParam password: Optional<String>): ResponseEntity<Account> {
Autre possibilité : on prend le nom ou l'id associé à un compte, puis les autres données en paramètres tel que :
`animaliste.fr/dupont?mail=exemple@mail.fr&password=123` ou `animaliste.fr/ID?mail=exemple@mail.fr&password=123` nous retourne le compte voulu.

2021-01-04 23:06 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getOneAccountByMail(@PathVariable("mail") mail: String, @RequestParam password: Optional<String>): ResponseEntity<Account> {
Je connais pas la pratique, Je crois que c'est pas dans l'url mais dans un body je pense :o
Genre /comptes/connect (et en body le mail + psw ) [ avec peut etre un autre nom que connect ]

2021-01-04 23:24 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getOneAccountByMail(@PathVariable("mail") mail: String, @RequestParam password: Optional<String>): ResponseEntity<Account> {
Mince j'ai même pas pris le point de vu d'une connexion j'suis débile.
T'as raison du coup pour le body.
La meilleur manière ce serait un body en param et un renvoie d'un booleen plutôt qu'une réponse http ?

2021-01-04 23:26 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/entities/Account.kt
> +    val name: String,
J'ai laissé le nom en obligatoire, je pense qu'une vérification de l'identité de façon plus "humaine" serait utile

2021-01-05 19:49 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getOneAccountByMail(@PathVariable("mail") mail: String, @RequestParam password: Optional<String>): ResponseEntity<Account> {
La réponse HTTP peux etre bonne [https://stackoverflow.com/a/1960453](https://stackoverflow.com/a/1960453)

2021-01-06 09:44 UTC, Prakkkmak requested changes

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/repositories/AccountRepository.kt
> +    fun findAccountByMailEquals(mail: String): Optional<Account>
```suggestion
    fun findAccountByMail(mail: String): Optional<Account>
```
Le nom findAccountByMailEquals est super bizare

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/repositories/AccountRepository.kt
> +    fun findAccountByMailEqualsAndPasswordEquals(mail: String, password: String): Optional<Account>
```suggestion
    fun findAccountByMailEqualsAndPassword(mail: String, password: String): Optional<Account>
```

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/entities/Account.kt
> +
```suggestion
```

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +     * Retourne le compte correspondant au couple mail/mot de passe ssi celui-ci existe ou un message d'erreur
```suggestion
     * Retourne le compte correspondant au couple mail/mot de passe ssi celui-ci existe ou un message d'erreur.
```

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/entities/AccountLoginForm.kt
> +data class AccountLoginForm(
Cette classe me gène, je comprends ton envie de mettre en dehors du body les params de la création d'account. Genre avec l'url /accounts/?mail="blah"password=""
Ca nous éviterai de créer une classe juste pour ça.
Je sais pas trop comment faire :/

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getAllAccounts(): ResponseEntity<List<Account>>{
```suggestion
    fun getAccounts(): ResponseEntity<List<Account>>{
```
Je sais que dans le controller de l'animal les noms sont pareil mais je pense qu'il faut changer

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getOneAccountById(@PathVariable("id") id: String): ResponseEntity<Account> {
```suggestion
    fun getAccount(@PathVariable("id") id: String): ResponseEntity<Account> {
```
Le prototype de la méthode est assez explicite. Pas besoin de dire byId. De plus , by id est la maniere de base.

2021-01-06 09:44 UTC, Prakkkmak commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getOneAccountByLoginForm(@RequestBody account: AccountLoginForm): ResponseEntity<Any> {
Tu sais si kotlin Spring accepte la surcharge de méthode ?

2021-01-06 19:19 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/entities/AccountLoginForm.kt
> +data class AccountLoginForm(
Je remets comme j'avais fait avant du coup, mais avec une route différente (`/accounts/login?mail=x&password=y`).

2021-01-06 19:22 UTC, BastienLamour commented on src/main/kotlin/com/progreizh/animaliste/controllers/AccountController.kt
> +    fun getOneAccountByLoginForm(@RequestBody account: AccountLoginForm): ResponseEntity<Any> {
J'avais regardé, selon plusieurs topics, je me rappelle plus lesquels, c'est pas possible de surcharger une requête HTTP ou pas conseillé. De toute façon j'ai changé la route donc ça pose pas de pb normalement.

2021-01-06 20:41 UTC, BastienLamour commented
![](https://github.trello.services/images/mini-trello-icon.png) [Jeu de données Comptes et TU](https://trello.com/c/btFRY6KX/48-jeu-de-donn%C3%A9es-comptes-et-tu)

2021-01-06 21:22 UTC, merged